[package]
name = "native-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csbindgen = "1.9.3"
bindgen = "0.69.4"